project_id = "zgyxybgogjzeuocuoane"

[functions.get-mapbox-token]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.verify-zippy-pass-payment]
verify_jwt = false
