project_id = "zgyxybgogjzeuocuoane"

[functions.get-mapbox-token]
verify_jwt = false

[functions.get-google-maps-key]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.verify-zippy-pass-payment]
verify_jwt = false

[functions.process-razorpay-refund]
verify_jwt = false

[functions.send-msg91-otp]
verify_jwt = false
